duck:
    resource: "@DuckBundle/Controller/"
    type:     annotation
    prefix:   /

observer_pattern:
    resource: "@ObserverPatternBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
