template_method:
    resource: "@TemplateMethodBundle/Controller/"
    type:     annotation
    prefix:   /

adapter_facade:
    resource: "@AdapterFacadeBundle/Controller/"
    type:     annotation
    prefix:   /adapt

remote_control:
    resource: "@RemoteControlBundle/Controller/"
    type:     annotation
    prefix:   /remote

chocolate:
    resource: "@ChocolateBundle/Controller/"
    type:     annotation
    prefix:   /chocolate

factory:
    resource: "@FactoryBundle/Controller/"
    type:     annotation
    prefix:   /factory

decorator:
    resource: "@DecoratorBundle/Controller/"
    type:     annotation
    prefix:   /decorator

duck:
    resource: "@DuckBundle/Controller/"
    type:     annotation
    prefix:   /duck

observer_pattern:
    resource: "@ObserverPatternBundle/Controller/"
    type:     annotation
    prefix:   /observer

app:
    resource: '@AppBundle/Controller/'
    type: annotation
