factory:
    resource: "@SimpleFactoryBundle/Controller/"
    type:     annotation
    prefix:   /

decorator:
    resource: "@DecoratorBundle/Controller/"
    type:     annotation
    prefix:   /

duck:
    resource: "@DuckBundle/Controller/"
    type:     annotation
    prefix:   /

observer_pattern:
    resource: "@ObserverPatternBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
